package scrapers

import "code/core"

var chaptersTableURLs = []string{
	"//www.revisor.mn.gov/statutes/part/JURISDICTION%252C+CIVIL+DIVISIONS",
	"//www.revisor.mn.gov/statutes/part/LEGISLATURE",
	"//www.revisor.mn.gov/statutes/part/CONSTITUTIONAL+OFFICES+AND+DUTIES",
	"//www.revisor.mn.gov/statutes/part/GOVERNMENT+MISCELLANY",
	"//www.revisor.mn.gov/statutes/part/DATA+PRACTICES",
	"//www.revisor.mn.gov/statutes/part/MEETINGS+OF+PUBLIC+BODIES",
	"//www.revisor.mn.gov/statutes/part/STATE+AGENCIES",
	"//www.revisor.mn.gov/statutes/part/CAPITOL+AREA",
	"//www.revisor.mn.gov/statutes/part/FRAUDULENT+STATE+CLAIMS",
	"//www.revisor.mn.gov/statutes/part/ADMINISTRATION+AND+FINANCE",
	"//www.revisor.mn.gov/statutes/part/AGRICULTURE",
	"//www.revisor.mn.gov/statutes/part/STATE+EMPLOYMENT",
	"//www.revisor.mn.gov/statutes/part/CITY+MERIT+SYSTEMS",
	"//www.revisor.mn.gov/statutes/part/COMMERCE",
	"//www.revisor.mn.gov/statutes/part/BANKING",
	"//www.revisor.mn.gov/statutes/part/INSURANCE",
	"//www.revisor.mn.gov/statutes/part/SECURITIES",
	"//www.revisor.mn.gov/statutes/part/COMMERCIAL+REGULATIONS",
	"//www.revisor.mn.gov/statutes/part/REAL+ESTATE+SALES+REGULATIONS",
	"//www.revisor.mn.gov/statutes/part/NATURAL+RESOURCES",
	"//www.revisor.mn.gov/statutes/part/CONSERVATION",
	"//www.revisor.mn.gov/statutes/part/RECREATION",
	"//www.revisor.mn.gov/statutes/part/FORESTRY",
	"//www.revisor.mn.gov/statutes/part/LANDS+AND+MINERALS",
	"//www.revisor.mn.gov/statutes/part/GAME+AND+FISH",
	"//www.revisor.mn.gov/statutes/part/WATER",
	"//www.revisor.mn.gov/statutes/part/ENVIRONMENTAL+PROTECTION",
	"//www.revisor.mn.gov/statutes/part/ECONOMIC+DEVELOPMENT+AND+PLANNING",
	"//www.revisor.mn.gov/statutes/part/ENVIRONMENTAL+PROTECTION+FUNDS",
	"//www.revisor.mn.gov/statutes/part/BUSINESS+DEVELOPMENT",
	"//www.revisor.mn.gov/statutes/part/EMINENT+DOMAIN%253B+LOCAL+DEPOSITORIES+AND+INVESTMENTS",
	"//www.revisor.mn.gov/statutes/part/CHILDREN+AND+FAMILIES",
	"//www.revisor.mn.gov/statutes/part/EDUCATION+CODE%253A+PREKINDERGARTEN+-+GRADE+12",
	"//www.revisor.mn.gov/statutes/part/ARTS",
	"//www.revisor.mn.gov/statutes/part/LIBRARIES",
	"//www.revisor.mn.gov/statutes/part/POSTSECONDARY+EDUCATION",
	"//www.revisor.mn.gov/statutes/part/STATE+HISTORY",
	"//www.revisor.mn.gov/statutes/part/PROPRIETARY+SCHOOLS",
	"//www.revisor.mn.gov/statutes/part/HEALTH",
	"//www.revisor.mn.gov/statutes/part/TRANSPORTATION",
	"//www.revisor.mn.gov/statutes/part/LABOR%252C+INDUSTRY",
	"//www.revisor.mn.gov/statutes/part/MILITARY+AFFAIRS",
	"//www.revisor.mn.gov/statutes/part/VETERANS",
	"//www.revisor.mn.gov/statutes/part/ELECTIONS",
	"//www.revisor.mn.gov/statutes/part/EXAMINING+AND+LICENSING+BOARDS",
	"//www.revisor.mn.gov/statutes/part/UTILITIES",
	"//www.revisor.mn.gov/statutes/part/CARRIERS",
	"//www.revisor.mn.gov/statutes/part/FARM+PRODUCTS%252C+COMMERCIAL+PRACTICES",
	"//www.revisor.mn.gov/statutes/part/TELECOMMUNICATIONS",
	"//www.revisor.mn.gov/statutes/part/WEIGHTS+AND+MEASURES",
	"//www.revisor.mn.gov/statutes/part/SPORTS",
	"//www.revisor.mn.gov/statutes/part/CORRECTIONS",
	"//www.revisor.mn.gov/statutes/part/PUBLIC+WELFARE+AND+RELATED+ACTIVITIES",
	"//www.revisor.mn.gov/statutes/part/EMPLOYMENT+AND+ECONOMIC+DEVELOPMENT",
	"//www.revisor.mn.gov/statutes/part/TAXATION%252C+SUPERVISION%252C+DATA+PRACTICES",
	"//www.revisor.mn.gov/statutes/part/PROPERTY+TAXES",
	"//www.revisor.mn.gov/statutes/part/VARIOUS+STATE+TAXES+AND+PROGRAMS",
	"//www.revisor.mn.gov/statutes/part/EXCISE+AND+SALES+TAXES",
	"//www.revisor.mn.gov/statutes/part/PUBLIC+SAFETY",
	"//www.revisor.mn.gov/statutes/part/BUSINESS%252C+SOCIAL%252C+AND+CHARITABLE+ORGANIZATIONS",
	"//www.revisor.mn.gov/statutes/part/TRADE+REGULATIONS%252C+CONSUMER+PROTECTION",
	"//www.revisor.mn.gov/statutes/part/ANIMALS+AND+PROPERTY",
	"//www.revisor.mn.gov/statutes/part/GAMING",
	"//www.revisor.mn.gov/statutes/part/VACANCY+IN+PUBLIC+OFFICE",
	"//www.revisor.mn.gov/statutes/part/RETIREMENT",
	"//www.revisor.mn.gov/statutes/part/COURT+AND+FILING+FEES%253B+ATTESTATIONS",
	"//www.revisor.mn.gov/statutes/part/AERONAUTICS",
	"//www.revisor.mn.gov/statutes/part/RURAL+DEVELOPMENT",
	"//www.revisor.mn.gov/statutes/part/HUMAN+RIGHTS",
	"//www.revisor.mn.gov/statutes/part/CRIMINALS%253B+REHABILITATION",
	"//www.revisor.mn.gov/statutes/part/TOWNS",
	"//www.revisor.mn.gov/statutes/part/COUNTIES%252C+COUNTY+OFFICERS%252C+REGIONAL+AUTHORITIES",
	"//www.revisor.mn.gov/statutes/part/CITIES%252C+ORGANIZATION",
	"//www.revisor.mn.gov/statutes/part/CITIES%252C+GENERAL+GOVERNMENT",
	"//www.revisor.mn.gov/statutes/part/MUNICIPAL+PERSONNEL%252C+RETIREMENT",
	"//www.revisor.mn.gov/statutes/part/MUNICIPAL+FINANCE%252C+TAXATION%252C+SPECIAL+ASSESSMENTS",
	"//www.revisor.mn.gov/statutes/part/MUNICIPAL+PUBLIC+SAFETY",
	"//www.revisor.mn.gov/statutes/part/MUNICIPAL+PUBLIC+WORKS",
	"//www.revisor.mn.gov/statutes/part/MUNICIPAL+WELFARE%252C+RECREATION",
	"//www.revisor.mn.gov/statutes/part/LOCAL+PUBLIC+UTILITIES%252C+ENTERPRISES",
	"//www.revisor.mn.gov/statutes/part/LOCAL+GOVERNMENT+POLICE+POWERS",
	"//www.revisor.mn.gov/statutes/part/POLITICAL+SUBDIVISIONS%252C+GENERAL+PROVISIONS",
	"//www.revisor.mn.gov/statutes/part/LOCAL+ECONOMIC+DEVELOPMENT",
	"//www.revisor.mn.gov/statutes/part/MUNICIPALITIES",
	"//www.revisor.mn.gov/statutes/part/METROPOLITAN+AREA",
	"//www.revisor.mn.gov/statutes/part/PUBLIC+DEBT%253B+LOCAL+GOVERNMENT+AID",
	"//www.revisor.mn.gov/statutes/part/JUDICIARY",
	"//www.revisor.mn.gov/statutes/part/PROPERTY+AND+PROPERTY+INTERESTS",
	"//www.revisor.mn.gov/statutes/part/DOMESTIC+RELATIONS",
	"//www.revisor.mn.gov/statutes/part/FIDUCIARIES%253B+POWERS+OF+ATTORNEY",
	"//www.revisor.mn.gov/statutes/part/PROBATE%253B+PROPERTY%253B+ESTATES%253B+GUARDIANSHIPS%253B+ANATOMICAL+GIFTS",
	"//www.revisor.mn.gov/statutes/part/CIVIL+PROCEDURE",
	"//www.revisor.mn.gov/statutes/part/DECLARATORY%252C+CORRECTIVE+AND+ADMINISTRATIVE+REMEDIES",
	"//www.revisor.mn.gov/statutes/part/POSTJUDGMENT+REMEDIES%253B+ALTERNATIVE+DISPUTE+RESOLUTION%253B+BONDS",
	"//www.revisor.mn.gov/statutes/part/EXTRAORDINARY+WRITS%253B+CONTEMPT%253B+POSTCONVICTION+RELIEF",
	"//www.revisor.mn.gov/statutes/part/JURIES",
	"//www.revisor.mn.gov/statutes/part/EVIDENCE",
	"//www.revisor.mn.gov/statutes/part/CIVIL+ACTIONS",
	"//www.revisor.mn.gov/statutes/part/CERTIORARI",
	"//www.revisor.mn.gov/statutes/part/CRIMES%253B+EXPUNGEMENT%253B+VICTIMS",
	"//www.revisor.mn.gov/statutes/part/CRIMINAL+PROCEDURE%253B+PEACE+OFFICERS%253B+PRIVACY+OF+COMMUNICATIONS",
	"//www.revisor.mn.gov/statutes/part/LOCAL+JAIL+FACILITIES%253B+LOCKUPS%253B+WORKHOUSE%253B+JUVENILE+OFFENDER+CARE%253B+PARDONS",
	"//www.revisor.mn.gov/statutes/part/STATUTES%252C+CONSTRUCTION",
}

var chaptersShortTableURLs = []string{
	"//www.revisor.mn.gov/statutes/cite/1",
	"//www.revisor.mn.gov/statutes/cite/2",
	"//www.revisor.mn.gov/statutes/cite/2A",
}

var sectionsTableURLs = []string{
	"/statutes/cite/1.01",
	"/statutes/cite/1.02",
	"/statutes/cite/1.03",
	"/statutes/cite/1.041",
	"/statutes/cite/1.042",
	"/statutes/cite/1.043",
	"/statutes/cite/1.0431",
	"/statutes/cite/1.044",
	"/statutes/cite/1.045",
	"/statutes/cite/1.0451",
	"/statutes/cite/1.046",
	"/statutes/cite/1.047",
	"/statutes/cite/1.048",
	"/statutes/cite/1.049",
	"/statutes/cite/1.05",
	"/statutes/cite/1.12",
	"/statutes/cite/1.13",
	"/statutes/cite/1.135",
	"/statutes/cite/1.141",
	"/statutes/cite/1.142",
	"/statutes/cite/1.143",
	"/statutes/cite/1.145",
	"/statutes/cite/1.146",
	"/statutes/cite/1.1465",
	"/statutes/cite/1.147",
	"/statutes/cite/1.1471",
	"/statutes/cite/1.1475",
	"/statutes/cite/1.148",
	"/statutes/cite/1.1485",
	"/statutes/cite/1.149",
	"/statutes/cite/1.1495",
	"/statutes/cite/1.1496",
	"/statutes/cite/1.1497",
	"/statutes/cite/1.1498",
	"/statutes/cite/1.1499",
	"/statutes/cite/1.15",
	"/statutes/cite/1.16",
	"/statutes/cite/1.21",
	"/statutes/cite/1.22",
	"/statutes/cite/1.23",
	"/statutes/cite/1.26",
	"/statutes/cite/1.27",
	"/statutes/cite/1.50",
	"/statutes/cite/1.51",
}

var sectionWithSubSectionsStatute = core.Statute{
	Chapter: "1",
	Section: "142",
	Title:   "STATE FLOWER.",
	Subdivisions: []core.Subdivision{
		{
			Number:  1,
			Heading: "Lady slipper.",
			Content: "The pink and white lady slipper, Cypripedium reginae, is the official flower of the state of Minnesota.",
		},
		{
			Number:  2,
			Heading: "Photograph.",
			Content: "A photograph of the pink and white lady slipper, obtained and approved by the commissioner of natural resources, shall be preserved in the Office of the Secretary of State.",
		},
	},
}

var sectionWithRepealedSubSectionsStatute = core.Statute{
	Chapter: "3C",
	Section: "035",
	Title:   "BILL DRAFTING FOR DEPARTMENTS AND AGENCIES.",
	Subdivisions: []core.Subdivision{
		{
			Number:  1,
			Heading: "Deadlines.",
			Content: "A department or agency intending to urge the legislature to adopt a bill shall deliver the drafting request for the bill to the revisor of statutes by November 1 before the regular session of the legislature at which adoption will be urged. A commissioner or agency head, however, may deliver a drafting request later by certifying to the revisor, with supporting facts, that the request is an emergency, relates to a matter that could not reasonably have been foreseen before November 1, or for which there is other reasonable justification for delay. The completed bill draft, in a form ready for introduction, must be delivered by the revisor to a senator or representative as directed by the department or agency. If the draft was requested after November 1, it must be accompanied by a copy of the commissioner's certification to the revisor.",
		},
		{
			Number:  3,
			Heading: "Restrictions on outside drafting.",
			Content: "A department or agency may not contract with an attorney, consultant, or other person either to provide drafting services to the department or agency or to advise on drafting unless the revisor determines that special expertise is required for the drafting and the expertise is not available from the revisor or the revisor's staff. A department or agency may not request legislative staff, other than the revisor of statutes, to provide drafting services to the department or agency.",
		},
	},
}

var sectionWithNoSubSectionsStatute = core.Statute{
	Chapter: "1",
	Section: "12",
	Title:   "FEDERAL FLOWAGE EASEMENTS OVER HIGHWAYS.",
	Subdivisions: []core.Subdivision{
		{
			Number:  -1,
			Heading: "",
			Content: "When requested by the commissioner of transportation the governor, in behalf of the state, may grant, bargain, sell, and convey to the United States of America any easement for flowage in and upon any easement or fee owned by the state of Minnesota for trunk highway right-of-way purposes when it is required by the United States to aid a public improvement.",
		},
	},
}
