package scrapers

import "code/core"

var chaptersTableURLs = []string{
	"https://www.revisor.mn.gov/statutes/part/JURISDICTION%252C+CIVIL+DIVISIONS",
	"https://www.revisor.mn.gov/statutes/part/LEGISLATURE",
	"https://www.revisor.mn.gov/statutes/part/CONSTITUTIONAL+OFFICES+AND+DUTIES",
	"https://www.revisor.mn.gov/statutes/part/GOVERNMENT+MISCELLANY",
	"https://www.revisor.mn.gov/statutes/part/DATA+PRACTICES",
	"https://www.revisor.mn.gov/statutes/part/MEETINGS+OF+PUBLIC+BODIES",
	"https://www.revisor.mn.gov/statutes/part/STATE+AGENCIES",
	"https://www.revisor.mn.gov/statutes/part/CAPITOL+AREA",
	"https://www.revisor.mn.gov/statutes/part/FRAUDULENT+STATE+CLAIMS",
	"https://www.revisor.mn.gov/statutes/part/ADMINISTRATION+AND+FINANCE",
	"https://www.revisor.mn.gov/statutes/part/AGRICULTURE",
	"https://www.revisor.mn.gov/statutes/part/STATE+EMPLOYMENT",
	"https://www.revisor.mn.gov/statutes/part/CITY+MERIT+SYSTEMS",
	"https://www.revisor.mn.gov/statutes/part/COMMERCE",
	"https://www.revisor.mn.gov/statutes/part/BANKING",
	"https://www.revisor.mn.gov/statutes/part/INSURANCE",
	"https://www.revisor.mn.gov/statutes/part/SECURITIES",
	"https://www.revisor.mn.gov/statutes/part/COMMERCIAL+REGULATIONS",
	"https://www.revisor.mn.gov/statutes/part/REAL+ESTATE+SALES+REGULATIONS",
	"https://www.revisor.mn.gov/statutes/part/NATURAL+RESOURCES",
	"https://www.revisor.mn.gov/statutes/part/CONSERVATION",
	"https://www.revisor.mn.gov/statutes/part/RECREATION",
	"https://www.revisor.mn.gov/statutes/part/FORESTRY",
	"https://www.revisor.mn.gov/statutes/part/LANDS+AND+MINERALS",
	"https://www.revisor.mn.gov/statutes/part/GAME+AND+FISH",
	"https://www.revisor.mn.gov/statutes/part/WATER",
	"https://www.revisor.mn.gov/statutes/part/ENVIRONMENTAL+PROTECTION",
	"https://www.revisor.mn.gov/statutes/part/ECONOMIC+DEVELOPMENT+AND+PLANNING",
	"https://www.revisor.mn.gov/statutes/part/ENVIRONMENTAL+PROTECTION+FUNDS",
	"https://www.revisor.mn.gov/statutes/part/BUSINESS+DEVELOPMENT",
	"https://www.revisor.mn.gov/statutes/part/EMINENT+DOMAIN%253B+LOCAL+DEPOSITORIES+AND+INVESTMENTS",
	"https://www.revisor.mn.gov/statutes/part/CHILDREN+AND+FAMILIES",
	"https://www.revisor.mn.gov/statutes/part/EDUCATION+CODE%253A+PREKINDERGARTEN+-+GRADE+12",
	"https://www.revisor.mn.gov/statutes/part/ARTS",
	"https://www.revisor.mn.gov/statutes/part/LIBRARIES",
	"https://www.revisor.mn.gov/statutes/part/POSTSECONDARY+EDUCATION",
	"https://www.revisor.mn.gov/statutes/part/STATE+HISTORY",
	"https://www.revisor.mn.gov/statutes/part/PROPRIETARY+SCHOOLS",
	"https://www.revisor.mn.gov/statutes/part/HEALTH",
	"https://www.revisor.mn.gov/statutes/part/TRANSPORTATION",
	"https://www.revisor.mn.gov/statutes/part/LABOR%252C+INDUSTRY",
	"https://www.revisor.mn.gov/statutes/part/MILITARY+AFFAIRS",
	"https://www.revisor.mn.gov/statutes/part/VETERANS",
	"https://www.revisor.mn.gov/statutes/part/ELECTIONS",
	"https://www.revisor.mn.gov/statutes/part/EXAMINING+AND+LICENSING+BOARDS",
	"https://www.revisor.mn.gov/statutes/part/UTILITIES",
	"https://www.revisor.mn.gov/statutes/part/CARRIERS",
	"https://www.revisor.mn.gov/statutes/part/FARM+PRODUCTS%252C+COMMERCIAL+PRACTICES",
	"https://www.revisor.mn.gov/statutes/part/TELECOMMUNICATIONS",
	"https://www.revisor.mn.gov/statutes/part/WEIGHTS+AND+MEASURES",
	"https://www.revisor.mn.gov/statutes/part/SPORTS",
	"https://www.revisor.mn.gov/statutes/part/CORRECTIONS",
	"https://www.revisor.mn.gov/statutes/part/PUBLIC+WELFARE+AND+RELATED+ACTIVITIES",
	"https://www.revisor.mn.gov/statutes/part/EMPLOYMENT+AND+ECONOMIC+DEVELOPMENT",
	"https://www.revisor.mn.gov/statutes/part/TAXATION%252C+SUPERVISION%252C+DATA+PRACTICES",
	"https://www.revisor.mn.gov/statutes/part/PROPERTY+TAXES",
	"https://www.revisor.mn.gov/statutes/part/VARIOUS+STATE+TAXES+AND+PROGRAMS",
	"https://www.revisor.mn.gov/statutes/part/EXCISE+AND+SALES+TAXES",
	"https://www.revisor.mn.gov/statutes/part/PUBLIC+SAFETY",
	"https://www.revisor.mn.gov/statutes/part/BUSINESS%252C+SOCIAL%252C+AND+CHARITABLE+ORGANIZATIONS",
	"https://www.revisor.mn.gov/statutes/part/TRADE+REGULATIONS%252C+CONSUMER+PROTECTION",
	"https://www.revisor.mn.gov/statutes/part/ANIMALS+AND+PROPERTY",
	"https://www.revisor.mn.gov/statutes/part/GAMING",
	"https://www.revisor.mn.gov/statutes/part/VACANCY+IN+PUBLIC+OFFICE",
	"https://www.revisor.mn.gov/statutes/part/RETIREMENT",
	"https://www.revisor.mn.gov/statutes/part/COURT+AND+FILING+FEES%253B+ATTESTATIONS",
	"https://www.revisor.mn.gov/statutes/part/AERONAUTICS",
	"https://www.revisor.mn.gov/statutes/part/RURAL+DEVELOPMENT",
	"https://www.revisor.mn.gov/statutes/part/HUMAN+RIGHTS",
	"https://www.revisor.mn.gov/statutes/part/CRIMINALS%253B+REHABILITATION",
	"https://www.revisor.mn.gov/statutes/part/TOWNS",
	"https://www.revisor.mn.gov/statutes/part/COUNTIES%252C+COUNTY+OFFICERS%252C+REGIONAL+AUTHORITIES",
	"https://www.revisor.mn.gov/statutes/part/CITIES%252C+ORGANIZATION",
	"https://www.revisor.mn.gov/statutes/part/CITIES%252C+GENERAL+GOVERNMENT",
	"https://www.revisor.mn.gov/statutes/part/MUNICIPAL+PERSONNEL%252C+RETIREMENT",
	"https://www.revisor.mn.gov/statutes/part/MUNICIPAL+FINANCE%252C+TAXATION%252C+SPECIAL+ASSESSMENTS",
	"https://www.revisor.mn.gov/statutes/part/MUNICIPAL+PUBLIC+SAFETY",
	"https://www.revisor.mn.gov/statutes/part/MUNICIPAL+PUBLIC+WORKS",
	"https://www.revisor.mn.gov/statutes/part/MUNICIPAL+WELFARE%252C+RECREATION",
	"https://www.revisor.mn.gov/statutes/part/LOCAL+PUBLIC+UTILITIES%252C+ENTERPRISES",
	"https://www.revisor.mn.gov/statutes/part/LOCAL+GOVERNMENT+POLICE+POWERS",
	"https://www.revisor.mn.gov/statutes/part/POLITICAL+SUBDIVISIONS%252C+GENERAL+PROVISIONS",
	"https://www.revisor.mn.gov/statutes/part/LOCAL+ECONOMIC+DEVELOPMENT",
	"https://www.revisor.mn.gov/statutes/part/MUNICIPALITIES",
	"https://www.revisor.mn.gov/statutes/part/METROPOLITAN+AREA",
	"https://www.revisor.mn.gov/statutes/part/PUBLIC+DEBT%253B+LOCAL+GOVERNMENT+AID",
	"https://www.revisor.mn.gov/statutes/part/JUDICIARY",
	"https://www.revisor.mn.gov/statutes/part/PROPERTY+AND+PROPERTY+INTERESTS",
	"https://www.revisor.mn.gov/statutes/part/DOMESTIC+RELATIONS",
	"https://www.revisor.mn.gov/statutes/part/FIDUCIARIES%253B+POWERS+OF+ATTORNEY",
	"https://www.revisor.mn.gov/statutes/part/PROBATE%253B+PROPERTY%253B+ESTATES%253B+GUARDIANSHIPS%253B+ANATOMICAL+GIFTS",
	"https://www.revisor.mn.gov/statutes/part/CIVIL+PROCEDURE",
	"https://www.revisor.mn.gov/statutes/part/DECLARATORY%252C+CORRECTIVE+AND+ADMINISTRATIVE+REMEDIES",
	"https://www.revisor.mn.gov/statutes/part/POSTJUDGMENT+REMEDIES%253B+ALTERNATIVE+DISPUTE+RESOLUTION%253B+BONDS",
	"https://www.revisor.mn.gov/statutes/part/EXTRAORDINARY+WRITS%253B+CONTEMPT%253B+POSTCONVICTION+RELIEF",
	"https://www.revisor.mn.gov/statutes/part/JURIES",
	"https://www.revisor.mn.gov/statutes/part/EVIDENCE",
	"https://www.revisor.mn.gov/statutes/part/CIVIL+ACTIONS",
	"https://www.revisor.mn.gov/statutes/part/CERTIORARI",
	"https://www.revisor.mn.gov/statutes/part/CRIMES%253B+EXPUNGEMENT%253B+VICTIMS",
	"https://www.revisor.mn.gov/statutes/part/CRIMINAL+PROCEDURE%253B+PEACE+OFFICERS%253B+PRIVACY+OF+COMMUNICATIONS",
	"https://www.revisor.mn.gov/statutes/part/LOCAL+JAIL+FACILITIES%253B+LOCKUPS%253B+WORKHOUSE%253B+JUVENILE+OFFENDER+CARE%253B+PARDONS",
	"https://www.revisor.mn.gov/statutes/part/STATUTES%252C+CONSTRUCTION",
}

var chaptersShortTableURLs = []string{
	"https://www.revisor.mn.gov/statutes/cite/1",
	"https://www.revisor.mn.gov/statutes/cite/2",
	"https://www.revisor.mn.gov/statutes/cite/2A",
}

var sectionsTableURLs = []string{
	"https://www.revisor.mn.gov/statutes/cite/1.01",
	"https://www.revisor.mn.gov/statutes/cite/1.02",
	"https://www.revisor.mn.gov/statutes/cite/1.03",
	"https://www.revisor.mn.gov/statutes/cite/1.041",
	"https://www.revisor.mn.gov/statutes/cite/1.042",
	"https://www.revisor.mn.gov/statutes/cite/1.043",
	"https://www.revisor.mn.gov/statutes/cite/1.0431",
	"https://www.revisor.mn.gov/statutes/cite/1.044",
	"https://www.revisor.mn.gov/statutes/cite/1.045",
	"https://www.revisor.mn.gov/statutes/cite/1.0451",
	"https://www.revisor.mn.gov/statutes/cite/1.046",
	"https://www.revisor.mn.gov/statutes/cite/1.047",
	"https://www.revisor.mn.gov/statutes/cite/1.048",
	"https://www.revisor.mn.gov/statutes/cite/1.049",
	"https://www.revisor.mn.gov/statutes/cite/1.05",
	"https://www.revisor.mn.gov/statutes/cite/1.12",
	"https://www.revisor.mn.gov/statutes/cite/1.13",
	"https://www.revisor.mn.gov/statutes/cite/1.135",
	"https://www.revisor.mn.gov/statutes/cite/1.141",
	"https://www.revisor.mn.gov/statutes/cite/1.142",
	"https://www.revisor.mn.gov/statutes/cite/1.143",
	"https://www.revisor.mn.gov/statutes/cite/1.145",
	"https://www.revisor.mn.gov/statutes/cite/1.146",
	"https://www.revisor.mn.gov/statutes/cite/1.1465",
	"https://www.revisor.mn.gov/statutes/cite/1.147",
	"https://www.revisor.mn.gov/statutes/cite/1.1471",
	"https://www.revisor.mn.gov/statutes/cite/1.1475",
	"https://www.revisor.mn.gov/statutes/cite/1.148",
	"https://www.revisor.mn.gov/statutes/cite/1.1485",
	"https://www.revisor.mn.gov/statutes/cite/1.149",
	"https://www.revisor.mn.gov/statutes/cite/1.1495",
	"https://www.revisor.mn.gov/statutes/cite/1.1496",
	"https://www.revisor.mn.gov/statutes/cite/1.1497",
	"https://www.revisor.mn.gov/statutes/cite/1.1498",
	"https://www.revisor.mn.gov/statutes/cite/1.1499",
	"https://www.revisor.mn.gov/statutes/cite/1.15",
	"https://www.revisor.mn.gov/statutes/cite/1.16",
	"https://www.revisor.mn.gov/statutes/cite/1.21",
	"https://www.revisor.mn.gov/statutes/cite/1.22",
	"https://www.revisor.mn.gov/statutes/cite/1.23",
	"https://www.revisor.mn.gov/statutes/cite/1.26",
	"https://www.revisor.mn.gov/statutes/cite/1.27",
	"https://www.revisor.mn.gov/statutes/cite/1.50",
	"https://www.revisor.mn.gov/statutes/cite/1.51",
}

var sectionWithSubSectionsStatute = core.Statute{
	Chapter: "1",
	Section: "142",
	Title:   "STATE FLOWER.",
	Subdivisions: []core.Subdivision{
		{
			Number:  "1",
			Heading: "Lady slipper.",
			Content: "The pink and white lady slipper, Cypripedium reginae, is the official flower of the state of Minnesota.",
		},
		{
			Number:  "2",
			Heading: "Photograph.",
			Content: "A photograph of the pink and white lady slipper, obtained and approved by the commissioner of natural resources, shall be preserved in the Office of the Secretary of State.",
		},
	},
}

var sectionWithRepealedSubSectionsStatute = core.Statute{
	Chapter: "3C",
	Section: "035",
	Title:   "BILL DRAFTING FOR DEPARTMENTS AND AGENCIES.",
	Subdivisions: []core.Subdivision{
		{
			Number:  "1",
			Heading: "Deadlines.",
			Content: "A department or agency intending to urge the legislature to adopt a bill shall deliver the drafting request for the bill to the revisor of statutes by November 1 before the regular session of the legislature at which adoption will be urged. A commissioner or agency head, however, may deliver a drafting request later by certifying to the revisor, with supporting facts, that the request is an emergency, relates to a matter that could not reasonably have been foreseen before November 1, or for which there is other reasonable justification for delay. The completed bill draft, in a form ready for introduction, must be delivered by the revisor to a senator or representative as directed by the department or agency. If the draft was requested after November 1, it must be accompanied by a copy of the commissioner's certification to the revisor.",
		},
		{
			Number:  "3",
			Heading: "Restrictions on outside drafting.",
			Content: "A department or agency may not contract with an attorney, consultant, or other person either to provide drafting services to the department or agency or to advise on drafting unless the revisor determines that special expertise is required for the drafting and the expertise is not available from the revisor or the revisor's staff. A department or agency may not request legislative staff, other than the revisor of statutes, to provide drafting services to the department or agency.",
		},
	},
}

var sectionWithNoSubSectionsStatute = core.Statute{
	Chapter: "1",
	Section: "12",
	Title:   "FEDERAL FLOWAGE EASEMENTS OVER HIGHWAYS.",
	Subdivisions: []core.Subdivision{
		{
			Number:  "",
			Heading: "",
			Content: "When requested by the commissioner of transportation the governor, in behalf of the state, may grant, bargain, sell, and convey to the United States of America any easement for flowage in and upon any easement or fee owned by the state of Minnesota for trunk highway right-of-way purposes when it is required by the United States to aid a public improvement.",
		},
	},
}

var sectionWithTablesStatute = core.Statute{
	Chapter: "28A",
	Section: "08",
	Title:   "LICENSE FEES; PENALTIES.",
	Subdivisions: []core.Subdivision{
		{
			Number:  "1",
			Heading: "General.",
			Content: "License fees, penalties for late renewal of licenses, and penalties for not obtaining a license before conducting business in food handling that are set in this section apply to the sections named except as provided under section 28A.09. Except as specified herein, bonds and assessments based on number of units operated or volume handled or processed which are provided for in said laws shall not be affected, nor shall any penalties for late payment of said assessments, nor shall inspection fees, be affected by this chapter. The penalties may be waived by the commissioner. Fees for all new licenses must be based on the anticipated future gross annual food sales. If a firm is found to be operating for multiple years without paying license fees, the state may collect the appropriate fees and penalties for each year of operation.",
		},
		{
			Number:  "3",
			Heading: "Fees effective July 1, 2003.",
			Content: ",,,,Penalties\n,Type of food handler,,License Fee Effective July 1, 2003,Late Renewal,NoLicense\n1.,Retail food handler or custom exempt food handler,,,,\n,(a) Having gross sales of only prepackaged nonperishable food of less than $15,000 for the immediately previous license or fiscal year and filing a statement with the commissioner,,$ 50,$ 17,$ 33\n,(b) Having under $15,000 gross sales or service including food preparation or having $15,000 to $50,000 gross sales or service for the immediately previous license or fiscal year,,$ 77,$ 25,$ 51\n,(c) Having $50,001 to $250,000 gross sales or service for the immediately previous license or fiscal year,,$155,$ 51,$102\n,(d) Having $250,001 to $1,000,000 gross sales or service for the immediately previous license or fiscal year,,$276,$ 91,$182\n,(e) Having $1,000,001 to $5,000,000 gross sales or service for the immediately previous license or fiscal year,,$799,$264,$527\n,(f) Having $5,000,001 to $10,000,000 gross sales or service for the immediately previous license or fiscal year,,$1,162,$383,$767\n,(g) Having $10,000,001 to $15,000,000 gross sales or service for the immediately previous license or fiscal year,,$1,376,$454,$908\n,(h) Having $15,000,001 to $20,000,000 gross sales or service for the immediately previous license or fiscal year,,$1,607,$530,$1,061\n,(i) Having $20,000,001 to $25,000,000 gross sales or service for the immediately previous license or fiscal year,,$1,847,$610,$1,219\n,(j) Having over $25,000,001 gross sales or service for the immediately previous license or fiscal year,,$2,001,$660,$1,321\n2.,Wholesale food handler,,,,\n,(a) Having gross sales or service of less than $25,000 for the immediately previous license or fiscal year,,$ 57,$ 19,$ 38\n,(b) Having $25,001 to $250,000 gross sales or service for the immediately previous license or fiscal year,,$284,$ 94,$187\n,(c) Having $250,001 to $1,000,000 gross sales or service from a mobile unit without a separate food facility for the immediately previous license or fiscal year,,$444,$147,$293\n,(d) Having $250,001 to $1,000,000 gross sales or service not covered under paragraph (c) for the immediately previous license or fiscal year,,$590,$195,$389\n,(e) Having $1,000,001 to $5,000,000 gross sales or service for the immediately previous license or fiscal year,,$769,$254,$508\n,(f) Having $5,000,001 to $10,000,000 gross sales or service for the immediately previous license or fiscal year,,$920,$304,$607\n,(g) Having $10,000,001 to $15,000,000 gross sales or service for the immediately previous license or fiscal year,,$990,$327,$653\n,(h) Having $15,000,001 to $20,000,000 gross sales or service for the immediately previous license or fiscal year,,$1,156,$381,$763\n,(i) Having $20,000,001 to $25,000,000 gross sales or service for the immediately previous license or fiscal year,,$1,329,$439,$877\n,(j) Having over $25,000,001 or more gross sales or service for the immediately previous license or fiscal year,,$1,502,$496,$991\n3.,Food broker,,$150,$ 50,$ 99\n4.,Wholesale food processor or manufacturer,,,,\n,(a) Having gross sales or service of less than $125,000 for the immediately previous license or fiscal year,,$169,$ 56,$112\n,(b) Having $125,001 to $250,000 gross sales or service for the immediately previous license or fiscal year,,$392,$129,$259\n,(c) Having $250,001 to $1,000,000 gross sales or service for the immediately previous license or fiscal year,,$590,$195,$389\n,(d) Having $1,000,001 to $5,000,000 gross sales or service for the immediately previous license or fiscal year,,$769,$254,$508\n,(e) Having $5,000,001 to $10,000,000 gross sales or service for the immediately previous license or fiscal year,,$920,$304,$607\n,(f) Having $10,000,001 to $15,000,000 gross sales or service for the immediately previous license or fiscal year,,$1,377,$454,$909\n,(g) Having $15,000,001 to $20,000,000 gross sales or service for the immediately previous license or fiscal year,,$1,608,$531,$1,061\n,(h) Having $20,000,001 to $25,000,000 gross sales or service for the immediately previous license or fiscal year,,$1,849,$610,$1,220\n,(i) Having $25,000,001 to $50,000,000 gross sales or service for the immediately previous license or fiscal year,,$2,090,$690,$1,379\n,(j) Having $50,000,001 to $100,000,000 gross sales or service for the immediately previous license or fiscal year,,$2,330,$769,$1,538\n,(k) Having $100,000,000 or more gross sales or service for the immediately previous license or fiscal year,,$2,571,$848,$1,697\n5.,Wholesale food processor of meat or poultry products under supervision of the U.S. Department of Agriculture,,,,\n,(a) Having gross sales or service of less than $125,000 for the immediately previous license or fiscal year,,$112,$ 37,$ 74\n,(b) Having $125,001 to $250,000 gross sales or service for the immediately previous license or fiscal year,,$214,$ 71,$141\n,(c) Having $250,001 to $1,000,000 gross sales or service for the immediately previous license or fiscal year,,$333,$110,$220\n,(d) Having $1,000,001 to $5,000,000 gross sales or service for the immediately previous license or fiscal year,,$425,$140,$281\n,(e) Having $5,000,001 to $10,000,000 gross sales or service for the immediately previous license or fiscal year,,$521,$172,$344\n,(f) Having $10,000,001 to $15,000,000 gross sales or service for the immediately previous license or fiscal year,,$765,$252,$505\n,(g) Having $15,000,001 to $20,000,000 gross sales or service for the immediately previous license or fiscal year,,$893,$295,$589\n,(h) Having $20,000,001 to $25,000,000 gross sales or service for the immediately previous license or fiscal year,,$1,027,$339,$678\n,(i) Having $25,000,001 to $50,000,000 gross sales or service for the immediately previous license or fiscal year,,$1,161,$383,$766\n,(j) Having $50,000,001 to $100,000,000 gross sales or service for the immediately previous license or fiscal year,,$1,295,$427,$855\n,(k) Having $100,000,001 or more gross sales or service for the immediately previous license or fiscal year,,$1,428,$471,$942\n6.,Wholesale food processor or manufacturer operating only at the State Fair,,$125,$ 40,$ 50\n7.,Wholesale food manufacturer having the permission of the commissioner to use the name Minnesota Farmstead cheese,,$ 30,$ 10,$ 15\n8.,Wholesale food manufacturer processing less than 700,000 pounds per year of raw milk,,$ 30,$ 10,$ 15\n9.,A milk marketing organization without facilities for processing or manufacturing that purchases milk from milk producers for delivery to a licensed wholesale food processor or manufacturer,,$ 50,$ 15,$ 25\n",
		},
		{
			Number:  "4",
			Heading: "Food handler license account; appropriation.",
			Content: "A food handler license account is established in the agricultural fund. Fees paid under subdivision 3 must be deposited in this account. Money in the account, including interest, is appropriated to the commissioner for expenses relating to licensing and inspecting food handlers under chapters 28 to 34A or rules adopted under one of those chapters.",
		},
	},
}

var emptyStatute = core.Statute{}
